model:
  _target_: src.modules.models.classification.Classifier
  model_name: "torchvision.models/mobilenet_v3_large"
  model_repo: null
  weights: "IMAGENET1K_V2"
  num_classes: 1
  freeze_layers: null

loss:
  _target_: "torch.nn.BCEWithLogitsLoss"

metrics:
  main:
    _target_: "torchmetrics.Accuracy"
    task: "binary"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
  additional:
    AUROC:
      _target_: "torchmetrics.AUROC"
      task: "binary"
    NDCG@10:
      _target_: "beir.evaluation.metrics.ndcg_at_k"
      k: 10

output_activation:
  _target_: "torch.sigmoid"

datamodules:
  - _target_: src.datamodules.gpl_lightning
  - _target_: src.datamodules.eval_lightning
  - _target_: src.datamodules.data_lightning

hydra:
  runtime: sequential
